config/routes.rb
WwApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :meetings
  resources :speakers, only: [:index, :create, :destroy]
  root :to => 'static_pages#home'
  match '/signup',    to: 'users#new',         via: 'get'
  match '/signin',    to: 'sessions#new',      via: 'get'
  match '/signout',   to: 'sessions#destroy',  via: 'delete'
  match '/agenda',    to: 'meetings#index',    via: 'get'
  match '/speakers',  to: 'speakers#index',    via: 'get'
  match '/attendees', to: 'users#index',       via: 'get'
  match '/maps',      to: 'static_pages#maps', via: 'get'

end

app/models/engagement.rb
class Engagement < ActiveRecord::Base
  belongs_to :speaker
  belongs_to :meeting

  validates :speaker_id, presence: true
  validates :meeting_id, presence: true
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  has_many :engagements, dependent: :destroy
  has_many :speakers, through: :engagements

  before_save :create_duration

  validates :title,     presence: true
  validates :location,  presence: true

  VALID_DATETIME_REGEX = /\A\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} [+-]*[\dA-z]{3,4}\z/
  validates :start_time,	presence: true,
  												format: { with: VALID_DATETIME_REGEX }
  # validates_is_after :start_time, :on => :create
  validates :end_time,		presence: true, 
  												format: { with: VALID_DATETIME_REGEX }
  validates_is_after :end_time, :after => :start_time

  def create_duration
  	self.duration = (self.end_time - self.start_time)
  end
end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
	has_many :engagements, dependent: :destroy
	has_many :meetings, through: :engagements
	
	validates :name, presence: true

	def scheduled?(meeting)
		engagements.find_by_meeting_id(meeting.id)
	end

	def schedule!(meeting)
		engagements.create!(meeting_id: meeting.id)
	end

	def unschedule!(meeting)
		engagements.find_by_meeting_id(meeting.id).destroy
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { email.downcase! }
  before_create :create_remember_token

  validates :first_name, :presence => true, length: { maximum: 50 }
  validates :last_name,  :presence => true, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true,
  									format: { with: VALID_EMAIL_REGEX },
  									uniqueness: { case_sensitive: false }
  
  has_secure_password
  validates :password, :length => { minimum: 8 },
  										 :presence => true,
                       :on => :create
  validates :password_confirmation, :presence => true, :on => :create 

  def User.new_remember_token
    SecureRandom::urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def admin_user
  	redirect_to(root_url) unless current_user.admin?
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
	before_filter :signed_in_user
	before_filter :admin_user, only: [:new, :create, :edit, :update, :destroy]

	def index
		@meetings = Meeting.order('start_time ASC, duration DESC').page(params[:page]).per_page(10)
	end

	def new
		@meeting = Meeting.new
	end

	def create
		@meeting = Meeting.new(meeting_params)
		if @meeting.save
  		flash[:success] = "Your event has been created."
  		redirect_to @meeting
  	else
  		render 'edit'
  	end
	end

	def show
		@meeting = Meeting.find(params[:id])
		@speakers = @meeting.speakers
		@speaker = @meeting.speakers.build
	end

	def edit
		@meeting = Meeting.find(params[:id])
	end

	def update
		@meeting = Meeting.find(params[:id])
		if @meeting.update_attributes(meeting_params)
      flash[:success] = "Meeting updated"
      redirect_to @meeting
    else
      render 'edit'
    end
	end

	def destroy
		Meeting.find(params[:id]).destroy
    flash[:success] = "Meeting deleted."
    redirect_to meetings_url
	end

	private
		def meeting_params
			params.require(:meeting).permit(:title, :location, :start_time,
																			:end_time, :description)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by_email(params[:email].downcase)
		if user && user.authenticate(params[:password])
			session[:user] = user.id
			sign_in user
			redirect_back_or user
		else
			flash.now[:error] = "Invalid email/password combination"
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_path
	end
end

app/controllers/speakers_controller.rb
class SpeakersController < ApplicationController
	before_filter :signed_in_user, only: [:create, :destroy]
	
	def index
		@speakers = Speaker.page(params[:page])
	end

	def create
		@meeting = Meeting.find(params[:meeting_id])
		@speaker = Speaker.new(speaker_params)
		if @speaker.save
			@speaker.schedule!(@meeting)
			flash[:success] = "Speaker saved!"
			redirect_to @meeting
		else
			redirect_to @meeting
		end
	end

	def destroy
	end

	private

	def speaker_params
		params.require(:speaker).permit(:name, :bio, :moderator, :user_id)
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user,          only: [:edit, :update]
  before_filter :correct_user,            only: [:edit, :update]
  before_filter :admin_user,              only: :destroy
  before_filter :skip_password_attribute, only: :update
  
  def index
    @users = User.page(params[:page])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      sign_in @user
  		flash[:success] = "Welcome to Woodrow Wilson Events!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  
  private

    # Requires that :user be a key in the params Hash and
 		# only accept :name, :email, :password, and :password_confirmation attr
  	def user_params
  		params.require(:user).permit(:first_name, :last_name, :email, :job_title,
                                   :employer, :bio, :current_project, :privacy,
  																 :password, :password_confirmation)
  	end

    # Before actions

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def skip_password_attribute
      if params[:password].blank? && params[:password_confirmation].blank?
        params.except!(:password, :password_confirmation)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "Woodrow Wilson Events"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = User.new_remember_token
		cookies[:remember_token] = { value: remember_token,
																 expires: 2.weeks.from_now.utc }
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by_remember_token(remember_token)
	end

	def current_user?(user)
		user == current_user
	end

	def signed_in_user
		unless signed_in?
			store_location
      redirect_to signin_url, notice: "Please sign in to access that page."
    end
  end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url if request.get?
	end
end

app/helpers/speakers_helper.rb
module SpeakersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

	def home
	end
end

app/helpers/users_helper.rb
module UsersHelper

	#Returns user's full name
	def full_name(user)
		user.first_name + ' ' + user.last_name
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		Woodrow Wilson Events by <a href="http://www.woodrow.org">Woodrow Wilson National Fellowship Foundation</a>
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", 		'#' %></li>
			<li><%= link_to "Contact",	'#' %></li>
			<li><a href="http://woodrow.org/news/">News</a></li>
			<li><%= link_to "Help",			'#' %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "Woodrow Wilson Events", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<% if signed_in? && current_user.admin? %>
						<li id="fat-menu" class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								Admin <b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to "Add New Meeting", new_meeting_path %></li>
								<li><%= link_to "Send New Alert",  '#' %></li>
							</ul>
						</li>
					<% end %>
					<% if signed_in? %>
						<li id="fat-menu" class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								Account <b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to "Profile", current_user %></li>
								<li><%= link_to "Settings", edit_user_path(current_user) %></li>
								<li class="divider"></li>
								<li><%= link_to "Sign out", signout_path, method: 'delete' %></li>
							</ul>
						</li>
					<% else %>
						<li><%= link_to "Sign in",	signin_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    "application", :media => "all",
	  																					"data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	  <%= render 'layouts/shim' %>
	</head>
	<body>
		<%   ##   Header            ## %>
		<%= render 'layouts/header' %>
		<div class="container">
			
			<% ##   Alerts & Errors   ## %>
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>

			<% ##   Main Content      ## %>
			<%= yield %>

			<% ##   Footer            ## %>
			<%= render 'layouts/footer' %>

			<% ## 	Debug Details 		## %>
			<%= debug(params) if Rails.env.development? %>
		</div>

	</body>
</html>

app/views/meetings/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :location %>
<%= f.text_field :location %>

<%= f.label :description %>
<%= f.text_area :description %>

<%= f.label :start_time %>
<%= f.date_select :start_time, :use_short_month => true %>
<%= f.time_select :start_time, :minute_step => 5, :ignore_date => true %>

<%= f.label :end_time %>
<%= f.date_select :end_time, :use_short_month => true %>
<%= f.time_select :end_time, :minute_step => 5, :ignore_date => true %>

app/views/meetings/_meeting.html.erb
<li>
	<p>
		<em><%= meeting.start_time %></em><br />
		<b><%= link_to meeting.title, meeting %></b><br />
		<%= meeting.location %><br />
		<% if current_user.admin? %>
			<%= link_to "edit this meeting", edit_meeting_path(meeting) %> | 
			<%= link_to "delete", meeting, method: :delete,
														data: { confirm: "Are you sure that you want to delete this meeting?" } %>
		<% end %>
	</p>
</li>

app/views/meetings/_speaker_form.html.erb
<%= form_for(@speaker) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.text_field :name, 		placeholder: "Mrs. Speaker Name X" %>
		<%= f.text_area  :bio, 			placeholder: "Speaker bio" %>
		<%= f.label :moderator, "Moderator?" %>
		<%= f.check_box  :moderator,	placeholder: "Moderator?" %>

    <%= hidden_field_tag "meeting_id", @meeting.id %>

	</div>
	<%= f.submit "Save Speaker", class: "btn btn-large btn-primary" %>
<% end %>

app/views/meetings/edit.html.erb
<% provide(:title, 'Edit Meeting') %>

<h1>Edit <%= @meeting.title %></h1>

<div class="row">
	<div class= "span6 offset3">
		<%= form_for(@meeting) do |f| %>
			<%= render 'meetings/fields', f: f %>
			<%= f.submit "Submit changes", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/meetings/index.html.erb
<% provide(:title, 'Agenda') %>
<h1>Agenda</h1>

<%= will_paginate(:class => "center pagination") %>

<ul class="meetings">
	<%= render @meetings %>
</ul>

<%= will_paginate(:class => "center pagination") %>

app/views/meetings/new.html.erb
<% provide(:title, 'Add New Meeting') %>
<h1>Create a New Meeting</h1>

<div class="row">
	<div class= "span6 offset3">
		<%= form_for(@meeting) do |f| %>
			<%= render 'meetings/fields', f: f %>
			<%= f.submit "Save Meeting", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/meetings/show.html.erb
<% provide(:title, @meeting.title) %>

<div class="row">
	<aside class="span4 offset1">
		<section>
			<h1><%= @meeting.title %></h1>
			<p>Title: <%= @meeting.title %></p>
			<p>Location: <%= @meeting.location %></p>
			<p>Start time: <%= @meeting.start_time %></p>
			<p>End time: <%= @meeting.end_time %></p>
			<p>Description: <%= @meeting.description %></p>
			<p><%= link_to "Edit this meeting", edit_meeting_path(@meeting) if current_user.admin? %></p>
		</section>
		<% if current_user.admin? %>
			<div class="row">
				<div class="span 4, offset1">
					<%= render 'speaker_form' %>
				</div>
			</div>
		<% end %>
	</aside>
	<div class="offset2 span4">
		<% if @meeting.speakers.any? %>
			<h3>Speakers (<%= @meeting.speakers.count %>)</h3>
			<ol class="speakers">
				<%= render @speakers %>
			</ol>
		<% end %>
	</div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li>* <%= msg %> </li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/speakers/_speaker.html.erb
<li>
	<p><b><%= speaker.name %></b></p>
	<p><%= speaker.bio %></p>
</li>

app/views/speakers/index.html.erb
<% provide(:title, 'Speakers') %>
<h1>Speakers</h1>

<%= will_paginate(:class => "center pagination") %>

<ul class="speakers">
	<%= render @speakers %>
</ul>

<%= will_paginate(:class => "center pagination") %>

app/views/static_pages/home.html.erb
<% if signed_in?  %>
	<div class="center hero-unit">
		<a href='/agenda'><h1>Agenda</h1></a>
	</div>
	<div class="center hero-unit">
		<a href='/speakers'><h1>Speakers</h1></a>
	</div>
	<div class="center hero-unit">
		<a href='/attendees'><h1>Attendees</h1></a>
	</div>
	<div class="center hero-unit">
		<a href='/maps'><h1>Maps</h1></a>
	</div>

<% else %>
	<div class="center hero-unit">

		<h1>Welcome to the Woodrow Wilson Event app!</h1>
		<h2>
		  This is the home page.
		</h2>

		<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
	</div>
<% end %>

app/views/static_pages/maps.html.erb
<% provide(:title, 'Maps') %>

<h1>Maps</h1>

<div class="center maps">
<h2>Perelman Quad</h2>
<p><%= image_tag("map_perelman_quad.gif", alt: "Perelman Quad") %></p>

<h2>Houston Hall</h2>
<p><%= image_tag("map_houston_hall_mtg_rms.png", alt: "Houston Hall") %></p>
</div>

app/views/users/_user.html.erb
<li>
	<%= link_to full_name(user), user %>
	<% if current_user.admin? && !current_user?(user) %>
		| <%= link_to "delete", user, method: :delete,
																 data: { confirm: "Are you sure you want to delete this user?" } %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit your profile') %>
<h1>Edit your profile</h1>

<div class="row">
	<div class= "span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :first_name %>
			<%= f.text_field :first_name %>

			<%= f.label :last_name %>
			<%= f.text_field :last_name %>

			<%= f.label :email %>
			<%= f.email_field :email %>

			<%= f.label :job_title %>
			<%= f.text_field :job_title %>

			<%= f.label :employer %>
			<%= f.text_field :employer %>

			<%= f.label :bio %>
			<%= f.text_area :bio %>

			<%= f.label :current_project %>
			<%= f.text_field :current_project %>

			<%= f.check_box :privacy %>
			<%= f.label(:privacy, "I do not want my email shared with conference participants.") %>
			
			<%= f.submit "Submit changes", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Attendees') %>
<h1>Attendees</h1>

<%= will_paginate(:class => "center pagination") %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate(:class => "center pagination") %>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign Up</h1>

<div class="row">
	<div class= "span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :first_name %>
			<%= f.text_field :first_name %>

			<%= f.label :last_name %>
			<%= f.text_field :last_name %>

			<%= f.label :email %>
			<%= f.email_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Create My Account!", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, full_name(@user)) %>

<div class="row">
	<div class="span4">
		<section>
			<h1><%= full_name(@user) %></h1>
		</section>
		<p>Email: <%= @user.email %></p>
		<p>Job title: <%= @user.job_title %></p>
		<p>Company/Employer: <%= @user.employer %></p>
		<p>Bio: <%= @user.bio %></p>
		<p>Current project: <%= @user.current_project %></p>
		
		<% if @user.privacy == true %>
			<p>Your email is currently <strong>private</strong>.</p>
		<% end %>
		
		<p><%= link_to "Edit your info", edit_user_path(@user) %></p>
	</div>
</div>